spring:
  application:
    name: MultiDBApp

db:
  data-sources:
    - name: db-1
      strategy: postgres
      url: jdbc:postgresql://app-db-1:5432/multidbapp
      table: users
      user: postgres
      password: postgres
      mapping:
        id: id
        username: username_test
        name: first_name
        surname: last_name

    - name: db-2
      strategy: postgres
      url: jdbc:postgresql://app-db-2:5432/multidbapp1
      table: staff
      user: postgres
      password: postgres
      mapping:
        id: staff-id
        username: staff-login
        name: staff-firstname
        surname: staff-lastname

    - name: db-3
      strategy: mysql
      url: jdbc:mysql://app-db-3:3306/multidbapp
      table: users-mysql
      user: user
      password: user
      mapping:
        id: idusers-mysql
        username: users-username
        name: users-name
        surname: users-surname
